// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mdxqccftcmwlwpcmionp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1keHFjY2Z0Y213bHdwY21pb25wIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM3MDI4NzEsImV4cCI6MjA1OTI3ODg3MX0.RroHIpll9Bpw4Fi7sCesrQ6UT0122iLB2yo3m8R1jNk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);